name: stock

channels:
  - conda-forge
  - hargup/label/pypi

dependencies:
  - numpy
  - scipy
  - matplotlib
  - fastnumbers
  - seaborn
  - pytidylib
  - beautifulsoup4
  - pandas
  - requests
  - pandas-datareader
  - yfinance
  - pymongo